### ISSUE TITLE
Doesn't work on Oreo

### ISSUE THREAD

**Issue by ghost** [emrsmsrli/Caffeine#5]
This is almost certainly due to the lack of a persistent notification. Any updates on adding that? I saw in a few Play Store reviews you said you were working on it, but that was a while ago.

**Comment by emrsmsrli** [comment]
Hello there, sorry for the inconvenience. I'm not sure I will add a persistent notification. Whole point of the app was to provide the original Caffeine experience without root and a persistent notification. With Oreo, this is not possible. Thanks for the attention. I will update the play store description and this repo readme.

**Comment by ghost** [comment]
Maybe you could add a setting to enable it?

**Comment by PorygonZRocks** [comment]
Maybe you could add a setting to enable it?

**Comment by emrsmsrli** [comment]
Hello again. 

I rewrote the whole app and added Android O support. Play Store update is on the way. You can try it and reply here if you encounter any errors.

Thanks.

**Comment by ghost** [comment]
Thanks! In my (very brief) testing, it seems to work. There is an issue: the notification disappeared almost immediately. It still kept the screen awake the one time I tested it, but it may be unreliable. Also, if you tap the icon again after the notification disappears, it starts flickering between the new time and old.

**Comment by emrsmsrli** [comment]
Hi.

Fixed those issues. Can you please try again and write a feedback here? Thanks.

**Comment by ghost** [comment]
Nope, the issues are still there. The notification lasts like a second or two longer, but it still disappears, and the flickering still happens (I can do a screen record in a second).

**Comment by ghost** [comment]
[Here](https://vgy.me/JtXllH.mp4)'s a screen recording of what I'm talking about.

**Comment by emrsmsrli** [comment]
Could you send me a logcat please? Because on my end the app works flawlessly. I could not understand the problem.

**Comment by ghost** [comment]
[Here](https://pastebin.com/raw/kdbcJUsz).

**Comment by emrsmsrli** [comment]
Issue should be gone now. TileService has a weird lifecycle. That was leaking some stuff. I moved timer related stuff into a new service. Let me know if you have any issues.

**Comment by ghost** [comment]
It works now, thanks!
